---
- name: Prepare facts and variables
  include_tasks: prepare.yml

- name: Install Net-SNMP and MIBS
  include_tasks: install_snmp.yml
  when: manoc_snmp_setup

- name: Install Manoc
  include_tasks: install.yml
